blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    toggle_activity,
)

app_name = BlogConfig.name

urlpatterns = [
    path("", PostListView.as_view(), name="post_list"),
    path("blog/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("create/", PostCreateView.as_view(), name="post_create"),
    path("update/<int:pk>/update/", PostUpdateView.as_view(), name="post_update"),
    path("delete/<int:pk>/delete/", PostDeleteView.as_view(), name="post_delete"),
    path("activity/<int:pk>/delete/", toggle_activity, name="toggle_activity"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls"), name="catalog"),
    path("blog/", include("blog.urls"), name="blog"),
    path("users/", include("users.urls"), name="users"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(
        max_length=150,
        verbose_name="Заголовок",
    )
    slug = models.SlugField(unique=True, max_length=150, blank=True)
    body = models.TextField(verbose_name="Содержание", blank=True, null=True)
    image = models.ImageField(
        upload_to="blog/photo",
        verbose_name="Превью",
        blank=True,
        null=True,
    )
    posted_at = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    is_published = models.BooleanField(
        default=True,
        verbose_name="Опубликован",
    )
    view_count = models.IntegerField(default=0, verbose_name="Просмотры")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=50, verbose_name="Название", help_text="Название категории"
    )
    description = models.TextField(
        verbose_name="Описание", help_text="Описание категории", blank=True, null=True
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    name = models.CharField(
        max_length=50, verbose_name="Название", help_text="Название продукта"
    )
    description = models.TextField(
        max_length=100,
        verbose_name="Описание",
        help_text="Описание продукта",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to="catalog/photo",
        verbose_name="Фото",
        help_text="Фото продукта",
        blank=True,
        null=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        related_name="products",
        blank=True,
        null=True,
    )
    price_for_buy = models.IntegerField(
        verbose_name="Цена за покупку", help_text="Цена за покупку продукта"
    )
    created_at = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    updated_at = models.DateTimeField(
        verbose_name="Дата последнего изменения", auto_now=True
    )
    manufactured_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата производства", blank=True, null=True
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name="Владелец",
        related_name="products",
        blank=True,
        null=True,
    )
    is_published = models.BooleanField(
        default=False, verbose_name="Опубликовано", help_text="Опубликовать продукт"
    )

    def __str__(self):
        return f"{self.name}: {self.price_for_buy} руб."

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "category"]
        permissions = [
            ("can_cancel_publication", "Can cancel publication of product"),
            ("can_change_description", "Can change description of product"),
            ("can_change_product_category", "Can change product category"),
        ]


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        related_name="versions",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Продукт",
    )
    version_number = models.CharField(
        max_length=10,
        verbose_name="Номер версии",
        help_text="Введите номер версии",
        null=True,
        blank=True,
    )
    version_name = models.CharField(
        max_length=100,
        verbose_name="Название версии",
        help_text="Введите название версии",
        null=True,
        blank=True,
    )
    is_version_active = models.BooleanField(
        default=False,
        verbose_name="Активная версия",
        help_text="Является ли версия активной",
    )

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["version_number", "version_name"]

    def __str__(self):
        return self.version_name

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from blog.models import Post


class PostListView(ListView):
    model = Post


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class PostCreateView(CreateView):
    model = Post
    fields = "__all__"
    success_url = reverse_lazy("blog:post_list")

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    fields = "__all__"
    success_url = reverse_lazy("blog:post_list")

    def get_success_url(self):
        return reverse("blog:post_detail", args=[self.kwargs.get("pk")])


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("blog:post_list")


def toggle_activity(request, pk):
    post_item = get_object_or_404(Post, pk=pk)
    if post_item.is_published:
        post_item.is_published = False
    else:
        post_item.is_published = True

    post_item.save()
    return redirect(reverse("blog:post_list"))

blog/templates/blog/post_confirm_delete.html
{% extends 'catalog/base.html'%}
{% block content%}

<div class="col-12">
<div class="container">
  <div class="row">
    <div class="col">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
          <div class="my-3 py-3">
          <h2 class="display-5"> Действительно хотите удалить "{{ object.name }}"?</h2>
          <div class="card-body">
            {% csrf_token %}
          </div>
            <button type="submit" class="btn btn-primary">Удалить</button>
            <a class="btn btn-primary" href="{% url 'catalog:product_list' %}" role="button">Отменить</a>
          </div>
        </div>
        </form>
    </div>
  </div>
</div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'catalog/base.html'%}
{% block content%}
{% load my_tags %}

<div class="col-12">
<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    <div class="text-bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <p class="card-text">Заголовок: {{ post.title }}</p>
              <p class="card-text"> Ссылка: {{ post.slug }}</p>
              <p class="card-text">Содержимое: {{ post.body }}</p>
              <p class="card-text">Опубликован: {{ post.is_published }}</p>
              <p class="card-text">Дата создания: {{ post.posted_at }}</p>
              <p class="card-text">Кол-во просмотров: {{ post.view_count }}</p>
    <div class="text-center overflow-hidden">
            <a class="btn btn-primary" href="{% url 'blog:post_list'%}" role="button">Назад</a>
        </div>
</div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="col-12">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'catalog/base.html'%}
{% load my_tags %}
{% block content%}
<a href="{% url 'blog:post_create' %}" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" >
            Создай свой пост
          </a>

<div class="col-12">
<div class="d-md-flex flex-md-equal w-100 my-md-3 ps-md-3">
    {% for post in object_list%}
    <div class="text-bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3">
        <h2 class="display-5"> {{ post.title }}</h2>
        <p class="lead"> {{ post.body }}</p>
      </div>
          <img src="{{ post.image | media_filter }}" width="800" height="600">
          <a class="btn btn-primary" href="{% url 'blog:post_detail' post.pk %}" role="button">Посмотреть</a>
          <a class="btn btn-primary" href="{% url 'blog:post_update' post.pk %}" role="button">Редактировать</a>
          <a class="btn btn-primary" href="{% url 'blog:post_delete' post.pk %}" role="button">Удалить</a>
        {% if post.is_published %}
            <a class="btn btn-success" href="{% url 'blog:toggle_activity' post.pk %}">Опубликован</a>
        {% else %}
            <a class="btn btn-warning" href="{% url 'blog:toggle_activity' post.pk %}">Неопубликован</a>
        {% endif %}
        {% endfor%}
    </div>
</div>
</div>
{% endblock %}